package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Consultas generated by hbm2java
 */
public class Consultas  implements java.io.Serializable {


     private Integer idConsultas;
     private Pacientes pacientes;
     private Date fechaYHora;
     private String resumen;

    public Consultas() {
    }

    public Consultas(Pacientes pacientes, Date fechaYHora, String resumen) {
       this.pacientes = pacientes;
       this.fechaYHora = fechaYHora;
       this.resumen = resumen;
    }
   
    public Integer getIdConsultas() {
        return this.idConsultas;
    }
    
    public void setIdConsultas(Integer idConsultas) {
        this.idConsultas = idConsultas;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public Date getFechaYHora() {
        return this.fechaYHora;
    }
    
    public void setFechaYHora(Date fechaYHora) {
        this.fechaYHora = fechaYHora;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }




}


