package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private PacienteId id;
     private String nombre;
     private Date fechaNacimiento;
     private Set<Consulta> consultas = new HashSet<>(0);

    public Paciente() {
    }

	
    public Paciente(PacienteId id, String nombre, Date fechaNacimiento) {
        this.id = id;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Paciente(PacienteId id, String nombre, Date fechaNacimiento, Set<Consulta> consultas) {
       this.id = id;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.consultas = consultas;
    }
   
    public PacienteId getId() {
        return this.id;
    }
    
    public void setId(PacienteId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set<Consulta> getConsultases() {
        return this.consultas;
    }
    
    public void setConsultases(Set<Consulta> consultases) {
        this.consultas = consultases;
    }




}


