package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private PacientesId id;
     private String nombre;
     private Date fechaNacimiento;
     private Set consultases = new HashSet(0);

    public Pacientes() {
    }

	
    public Pacientes(PacientesId id, String nombre, Date fechaNacimiento) {
        this.id = id;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Pacientes(PacientesId id, String nombre, Date fechaNacimiento, Set consultases) {
       this.id = id;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.consultases = consultases;
    }
   
    public PacientesId getId() {
        return this.id;
    }
    
    public void setId(PacientesId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getConsultases() {
        return this.consultases;
    }
    
    public void setConsultases(Set consultases) {
        this.consultases = consultases;
    }




}


