package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private Set cursoses = new HashSet(0);

    public Estudiantes() {
    }

	
    public Estudiantes(int codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Estudiantes(int codigo, String nombre, Set cursoses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.cursoses = cursoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set cursoses) {
        this.cursoses = cursoses;
    }




}


