package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiposPoliza generated by hbm2java
 */
public class TiposPoliza  implements java.io.Serializable {


     private int codigoPoliza;
     private String nombre;
     private String descripcion;
     private long montoMaximo;
     private Set polizasAprobadases = new HashSet(0);

    public TiposPoliza() {
    }

	
    public TiposPoliza(int codigoPoliza, String nombre, String descripcion, long montoMaximo) {
        this.codigoPoliza = codigoPoliza;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.montoMaximo = montoMaximo;
    }
    public TiposPoliza(int codigoPoliza, String nombre, String descripcion, long montoMaximo, Set polizasAprobadases) {
       this.codigoPoliza = codigoPoliza;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.montoMaximo = montoMaximo;
       this.polizasAprobadases = polizasAprobadases;
    }
   
    public int getCodigoPoliza() {
        return this.codigoPoliza;
    }
    
    public void setCodigoPoliza(int codigoPoliza) {
        this.codigoPoliza = codigoPoliza;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public long getMontoMaximo() {
        return this.montoMaximo;
    }
    
    public void setMontoMaximo(long montoMaximo) {
        this.montoMaximo = montoMaximo;
    }
    public Set getPolizasAprobadases() {
        return this.polizasAprobadases;
    }
    
    public void setPolizasAprobadases(Set polizasAprobadases) {
        this.polizasAprobadases = polizasAprobadases;
    }




}


